server:
  port: 8090
spring:
  thymeleaf:
    encoding: utf-8
    suffix: .html
    prefix: classpath:/templates
    servlet:
      content-type: text/html
    check-template-location: true

#logging:
#  config: logback.xml
#  level:
#    com.jasmine.boot: trace