server:
  port: 8090

spring:
  thymeleaf:
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.jasmine.boot.pojo


